### ISSUE TITLE
Issue in embedding

### ISSUE THREAD

**Issue by suriyavarman2** [JACOBIN-SCTCS/NLTODB#2]
File "D:\NLTODB-master\train.py", line 43, in <module>
    train_model(model,n_epochs,optimizer,train_dataloader,valid_dataloader,train_entry)
  File "D:\NLTODB-master\utils.py", line 130, in train_model
    scores = model(data['question_tokens'] , data['column_headers'] ,train_entry , data['where_col'] ,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\NLTODB-master\cuda\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\NLTODB-master\cuda\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\NLTODB-master\model.py", line 44, in forward
    embedding , length = self.wordembedding.gen_x_batch(question,columns)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\NLTODB-master\wordembedding.py", line 49, in gen_x_batch
    val_emb_array[i,j,:] = val_embs[i][j]
    ~~~~~~~~~~~~~^^^^^^^
ValueError: could not broadcast input array from shape (300,) into shape (50,)

**Comment by JACOBIN-SCTCS** [comment]
Have you changed the N_word variable in train.py from 50 to your glove embedding dimension ?

**Comment by suriyavarman2** [comment]
Changed and it's working.
 I have different database with me, Will this code work well if i change the datasets and train the model??

**Comment by JACOBIN-SCTCS** [comment]
You might have to bring your dataset to the format of the currently used..haven't tested the code on later versions of packages being used

**Comment by suriyavarman2** [comment]
Is there any code to create dataset in same format??

**Comment by JACOBIN-SCTCS** [comment]
You might have to refer the dataset inside the data folder and create a program on your own

**Comment by suriyavarman2** [comment]
Thank you!
